### ISSUE TITLE
toggle onboard

### ISSUE THREAD

**Issue by scurrvy2020** [ssmolkin1/i3touchmenu#4]
You can actually toggle onboard using DBUS.  It's explained here: http://bazaar.launchpad.net/~onboard/onboard/1.3/view/head:/README

I'm using this command:
dbus-send --type=method_call --print-reply --dest=org.onboard.Onboard /org/onboard/Onboard/Keyboard org.onboard.Onboard.Keyboard.ToggleVisible

**Comment by ssmolkin1** [comment]
Thanks, this works well! I'll updated the module to use this command.
